# Generated by Django 4.2.2 on 2024-08-22 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='numero',
            field=models.CharField(default=1, max_length=10, verbose_name='Digite el numero de ficha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prueba',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='ficha',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluacion.ficha'),
        ),
    ]
